### ISSUE TITLE
can not build getting:  Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved @babel/helper-compilation-targets/package.json

### ISSUE THREAD

**Issue by joeysmart** [timoschwarzer/gitlab-monitor#141]
Hi Timo:
I am getting following error:
 ERROR  Failed to compile with 1 errors                                                                                                      9:24:46 AM

 error  in ./src/main.js

Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main resolved in /home/nrgdev1/dev/gitlab-monitor/node_modules/@babel/helper-compilation-targets/package.json
    at applyExports (internal/modules/cjs/loader.js:491:9)
    at resolveExports (internal/modules/cjs/loader.js:507:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/nrgdev1/dev/gitlab-monitor/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/nrgdev1/dev/gitlab-monitor/node_modules/@babel/preset-env/lib/index.js:11:14)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)

 @ multi (webpack)-dev-server/client?http://10.10.0.29:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by joeysmart** [comment]
I have added 2 lines to Dockerfile then it worked:
RUN npm update && npm audit fix --force
RUN npm install --save date-fns

**Comment by timoschwarzer** [comment]
This project uses yarn 1.x as package manager. Have you installed the dependencies with yarn 1.x or another package manager?

**Comment by joeysmart** [comment]
Yes I am using yarn - I have found this fix with npm in the internet - everything is working perfect now, but I moved to newer versions for some packages. Sorry I have forgotten to close this issue.
Great Project!
