### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by armandleopold** [timoschwarzer/gitlab-monitor#143]
```
 [3/4] Linking dependencies...
 warning " > monaco-editor-webpack-plugin@1.7.0" has unmet peer dependency "webpack@^4.5.0".
 warning " > monaco-editor-webpack-plugin@1.7.0" has unmet peer dependency "monaco-editor@^0.15.1".
 warning " > file-loader@3.0.1" has unmet peer dependency "webpack@^4.0.0".
 warning " > sass-loader@8.0.2" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
 [4/4] Building fresh packages...
 Done in 127.58s.
 yarn run v1.22.4
 $ vue-cli-service build
 -  Building for production...
  ERROR  Failed to compile with 1 errors7:18:23 PM
  error  in ./src/main.js
 Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
 Thread Loader (Worker 0)
 [BABEL] /usr/src/app/src/main.js: No "exports" main resolved in /usr/src/app/node_modules/@babel/helper-compilation-targets/package.json (While processing: "/usr/src/app/node_modules/@vue/babel-preset-app/index.js")
     at PoolWorker.fromErrorObj (/usr/src/app/node_modules/thread-loader/dist/WorkerPool.js:262:12)
     at /usr/src/app/node_modules/thread-loader/dist/WorkerPool.js:204:29
     at applyExports (internal/modules/cjs/loader.js:491:9)
     at resolveExports (internal/modules/cjs/loader.js:507:23)
     at Function.Module._findPath (internal/modules/cjs/loader.js:635:31)
     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
     at Function.Module._load (internal/modules/cjs/loader.js:842:27)
     at Module.require (internal/modules/cjs/loader.js:1026:19)
     at require (internal/modules/cjs/helpers.js:72:18)
     at Object.<anonymous> (/usr/src/app/node_modules/@babel/preset-env/lib/debug.js:8:33)
     at Module._compile (internal/modules/cjs/loader.js:1138:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
  @ multi ./src/main.js
  ERROR  Build failed with errors.
 error Command failed with exit code 1.
```

**Comment by timoschwarzer** [comment]
Cannot reproduce. Please share more information.

**Comment by armandleopold** [comment]
Problem solved : 
I had to edit your Dockerfile : 
```
# Stage 1
FROM node:12-alpine as build

WORKDIR /usr/src/app
COPY gitlab-monitor/ ./
RUN npm install -D babel-loader @babel/core @babel/preset-env webpack
RUN yarn install
RUN yarn add @vue/babel-preset-app --save-dev
Run yarn build
```

I had also to edit you helm-chart because of some weird balise tag in the deployement.
